# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run run-test.sh
      run: sh run-test.sh

    - name: Run run-server-test.sh
      run: sh run-server-test.sh

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - uses: actions/hello-world-docker-action@master
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Run meeshkan tests
      id: meeshkan
      uses: meeshkan/action@master
      with:
        endpoint: 'http://localhost:8080/endpoint1'

    - name: Show the output meeshkan_time
      run: echo "The meeshkan_time was ${{ steps.meeshkan.outputs.meeshkan_time }}"
